version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - common
      - dependabot
    commit-message:
      prefix: "BAU"
    versioning-strategy: increase
    groups:
      prod-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "patch"
      dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@govuk-frontend"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: npm
    directory: /ui-automation-tests
    schedule:
      interval: daily
    labels:
      - ui-tests
      - dependabot
    commit-message:
      prefix: "BAU"
    versioning-strategy: increase
    groups:
      test-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - actions
      - dependabot
    commit-message:
      prefix: "BAU"
    groups:
      gha-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "12:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
      - docker
    commit-message:
      prefix: BAU
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"