name: Build

on: workflow_call
      
permissions: read-all

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Product pages
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-pages
          retention-days: 7
          path: |
            dist
            resources
            src/views
            assets/images
            package*.json
            manifest.yml

