name: Build frontend image

on:
  workflow_call:
    inputs:
      artifact-name: { required: true, type: string }
    secrets:
      dynatrace-pass-token: { required: true }
    outputs:
      image-uri:
        value: ${{ jobs.build.outputs.image-uri }}

concurrency:
  group: push-frontend-image-development-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Push image
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.push-image.outputs.image-uri }}

    environment:
      name: development
      url: ${{ steps.push-image.outputs.image-url }}

    steps:
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.dynatrace-pass-token }}

      - name: Push Docker image
        uses: govuk-one-login/github-actions/aws/ecr/build-docker-image@7e9f6ee1a1f7b30ca9cba4d3893d3ee6313decef # 9/07/2024
        id: push-image
        with:
          image-version: ${{ github.sha }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          repository: ${{ vars.FRONTEND_CONTAINER_IMAGE_REPOSITORY }}
          image-tags: "${{ github.head_ref || github.ref_name }}"
          dockerfile: Dockerfile
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: express/dist
