name: Check PR

on: pull_request
permissions:
  id-token: write
  contents: read

jobs:

  code-quality:
    name: Code quality
    uses: ./.github/workflows/check-code-quality.yml

  run-unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml

  deploy-branch:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-branch.yml
    secrets: inherit

  run-acceptance-tests:
    name: Run tests
    uses: ./.github/workflows/run-acceptance-tests.yml
    needs: [ deploy-branch ]
    with:
      host: ${{ needs.deploy-branch.outputs.ProductToolURL }}
      environment: preview

