name: Check PR

on: pull_request
permissions:
  id-token: write
  contents: read

jobs:

  build-frontend:
    name: build-Frontend
    permissions: { }
    uses: ./.github/workflows/build-frontend.yml

  push-frontend-image:
    name: push-Frontend
    needs: build-frontend
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      artifact-name: ${{ needs.build-frontend.outputs.artifact-name }}

  deploy-frontend:
    name: deploy-Frontend
    needs: [ push-frontend-image]
    uses: ./.github/workflows/deploy-component.yml
    with:
      name: Frontend
      deployment-url-output: ProductToolURL
      template: infrastructure/frontend/frontend.template.yml
      parameters: |
        ImageURI=${{ needs.push-frontend-image.outputs.image-uri }}
        LogGroupPrefix=/self-service/preview

  code-quality:
    name: Code quality
    needs: [ deploy-frontend ]
    uses: ./.github/workflows/check-code-quality.yml

  run-unit-tests:
    name: Run tests
    needs: [ deploy-frontend ]
    uses: ./.github/workflows/run-unit-tests.yml

  run-acceptance-tests:
    name: Run tests
    uses: ./.github/workflows/run-acceptance-tests.yml
    with:
      environment: ${{ needs.deploy-preview-frontend.outputs.environment }}

