name: Check code quality

on: workflow_call
permissions: read-all

concurrency:
  group: code-quality-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run-checkov:
    name: Checkov
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run checkov
        uses: alphagov/di-github-actions/code-quality/run-checkov@850483e1476abd3f77a74f75a33b0b2871c29955
        with:
          skip-checks: CKV_SECRET_6

  check-shell-scripts:
    name: Shell scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run shell checks
        uses: alphagov/di-github-actions/code-quality/check-shell-scripts@850483e1476abd3f77a74f75a33b0b2871c29955

  check-linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check linting and formatting
        uses: alphagov/di-github-actions/code-quality/check-linting@850483e1476abd3f77a74f75a33b0b2871c29955

  check-vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run security audit
        uses: alphagov/di-github-actions/code-quality/run-security-audit@850483e1476abd3f77a74f75a33b0b2871c29955
