name: Check PR

on: pull_request
permissions:
  id-token: write
  contents: read

jobs:
  #code-quality:
    #name: Code quality
    #uses: ./.github/workflows/check-code-quality.yml

  build-frontend:
    name: build-Frontend
    permissions: { }
    uses: ./.github/workflows/build-frontend.yml

  push-frontend-image:
    name: push-Frontend
    needs: build-frontend
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      artifact-name: ${{ needs.build-frontend.outputs.artifact-name }}

  run-unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml
