name: Check code quality

on: workflow_call
permissions: 
  id-token: write
  contents: read

concurrency:
  group: code-quality-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run-checkov:
    name: Checkov
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run checkov
        uses: govuk-one-login/github-actions/code-quality/run-checkov@1fcdedf31dcba8fca25be864d419e4d5e4f1485c # 16/04/2024
        with:
          skip-checks: CKV_SECRET_6

  check-shell-scripts:
    name: Shell scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run shell checks
        uses: govuk-one-login/github-actions/code-quality/check-shell-scripts@1fcdedf31dcba8fca25be864d419e4d5e4f1485c # 16/04/2024

  check-linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check linting and formatting
        uses: govuk-one-login/github-actions/code-quality/check-linting@1fcdedf31dcba8fca25be864d419e4d5e4f1485c # 16/04/2024

  check-vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run security audit
        uses: govuk-one-login/github-actions/code-quality/run-security-audit@1fcdedf31dcba8fca25be864d419e4d5e4f1485c # 16/04/2024
