name: Check PR

on: pull_request
permissions: read-all

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/check-code-quality.yml

  build:
    name: Build
    uses: ./.github/workflows/build-frontend.yml

  push-frontend-image:
    name: frontend
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      artifact-name: ${{ needs.build-frontend.outputs.artifact-name }}

  run-unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml
