name: Check code quality

on: workflow_call

concurrency:
  group: code-quality-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run-checkov:
    name: Checkov
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run checkov
        uses: alphagov/di-github-actions/code-quality/run-checkov@f678b164969e156ef894a4bb7e7cd052df01e607

  check-shell-scripts:
    name: Shell scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run shell checks
        uses: alphagov/di-github-actions/code-quality/check-shell-scripts@f678b164969e156ef894a4bb7e7cd052df01e607

  check-linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check linting and formatting
        uses: alphagov/di-github-actions/code-quality/check-linting@f678b164969e156ef894a4bb7e7cd052df01e607
