name: Clean up deployments
run-name: Delete stale deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: '0 10 * * 1-5'

concurrency: deploy-preview-${{ github.head_ref || github.ref_name }}
permissions: read-all

jobs:
  delete-deployments:
    name: Delete stale app previews
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: PaaS login
        uses: govuk-one-login/github-actions/paas/log-in-to-paas@850483e1476abd3f77a74f75a33b0b2871c29955
        with:
          cf-org-name: gds-digital-identity-onboarding
          cf-space-name: product-pages-preview
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}

      - name: Delete stale apps
        uses: govuk-one-login/github-actions/paas/delete-stale-apps@850483e1476abd3f77a74f75a33b0b2871c29955
        with:
          age-threshold-days: 30
          
