name: Clean up deployments
run-name: Delete stale deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: '0 10 * * 1-5'

concurrency: deploy-preview-${{ github.head_ref || github.ref_name }}
permissions: read-all

jobs:
  delete-deployments:
    name: Delete stale app previews
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: PaaS login
        uses: alphagov/di-github-actions/paas/log-in-to-paas@0d0014de496fbdf3bee8bedd5e524ad9391b7f5f
        with:
          cf-org-name: gds-digital-identity-onboarding
          cf-space-name: product-pages-preview
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}

      - name: Delete stale apps
        uses: alphagov/di-github-actions/paas/delete-stale-apps@0d0014de496fbdf3bee8bedd5e524ad9391b7f5f
        with:
          age-threshold-days: 30
