name: Clean-up-deployment
run-name:  Delete stale deployments 
on:
  workflow_dispatch:
  push:
  #pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
   delete-frontend:
    name: Frontend
    uses: ./.github/workflows/delete-sam-stack.yml
    with:
      component: Frontend
