name: Clean-up-deployment

run-name:  Delete stacks 


on:
  workflow_dispatch:
  schedule:
     #Every weekday at 10am
    - cron: '0 10 * * 1-5'

permissions:
  id-token: write
  contents: read

jobs:
   delete-frontend:
    name: Frontend
    uses: ./.github/workflows/delete-sam-stack.yml
    with:
      component: Frontend
