
name: Delete Preview Branches

on:
  workflow_dispatch:
  #pull_request:
  push:
    branches: [ test-previews ]

jobs:
  delete-previews-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List and Delete Previews Branches
      run: |
        previews_branches=$(git for-each-ref --format '%(refname:short)' refs/heads/*previews)
        # Check if there are any previews branches
        if [ -n "$previews_branches" ]; then
          for branch in $previews_branches; do
            echo "Deleting previews branch: $branch"
            git branch -d "$branch"
            git push origin --delete "$branch"
          done
        else
          echo "No previews branches found"
        fi
