name: Delete a SAM stack

on:
  workflow_call:
    inputs:
      component: { required: true, type: string }

concurrency: deploy-${{ inputs.component }}-development-${{ github.head_ref || github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Delete
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Get stack name
        uses: govuk-one-login/github-actions/beautify-branch-name@081ce732d75690781b1eb82d85ee11b45934c51e
        id: get-stack-name
        with:
          usage: Stack name
          prefix: preview-${{ inputs.component }}
          length-limit: 128

      - name: Delete stack
        uses: govuk-one-login/github-actions/sam/delete-stacks@081ce732d75690781b1eb82d85ee11b45934c51e
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          stack-names: ${{ steps.get-stack-name.outputs.pretty-branch-name }}
