name: Deploy to PaaS

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      cf-space-name: { required: true, type: string }
      app-name-prefix: { required: false, type: string }
      url: { required: false, type: string }
      instances: { required: false, type: number, default: 1 }
      rolling-deployment: { required: false, type: boolean, default: false }
      google-tag-id: { required: false, type: string, default: GTM-PFTQ6G2 }
      use-stub-zendesk: { required: false, type: boolean, default: true }
    secrets:
      cf-username: { required: true }
      cf-password: { required: true }
      register-spreadsheet-id: { required: true }
      mailing-list-spreadsheet-id: { required: true }
      zendesk-api-token: { required: false }
      zendesk-username: { required: false }
      zendesk-group-id: { required: false }
    outputs:
      environment:
        description: "The environment name the app was deployed to"
        value: ${{ inputs.environment }}
      deployment-url:
        description: "The PaaS deployment URL"
        value: ${{ jobs.deploy.outputs.deployment-url }}

concurrency: deploy-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}
permissions: read-all

jobs:
  deploy:
    name: Deploy to PaaS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.push-to-paas.outputs.deployment-url }}
    outputs:
      deployment-url: ${{ steps.push-to-paas.outputs.deployment-url }}
    steps:
      - name: Get distribution artifact
        uses: actions/download-artifact@v3
        with:
          name: product-pages

      - name: Push to PaaS
        id: push-to-paas
        uses: alphagov/di-github-actions/paas/deploy-app@0d0014de496fbdf3bee8bedd5e524ad9391b7f5f
        with:
          url: ${{ inputs.url }}
          app-name-prefix: ${{ inputs.app-name-prefix }}
          cf-org-name: gds-digital-identity-onboarding
          cf-space-name: ${{ inputs.cf-space-name }}
          cf-username: ${{ secrets.cf-username }}
          cf-password: ${{ secrets.cf-password }}
          instances: ${{ inputs.instances }}
          rolling-deployment: ${{ inputs.rolling-deployment }}
          variables: |
            register-spreadsheet-id = ${{ secrets.register-spreadsheet-id }}
            mailing-list-spreadsheet-id = ${{ secrets.mailing-list-spreadsheet-id }}
            zendesk-api-token = ${{ secrets.zendesk-api-token }}
            zendesk-username = ${{ secrets.zendesk-username }}
            zendesk-group-id = ${{ secrets.zendesk-group-id }}
            use-stub-zendesk = ${{ inputs.use-stub-zendesk }}
            google-tag-id = ${{ inputs.google-tag-id }}
