name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  run-unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml

  deploy-test:
    name: Test
    needs: [ build, run-unit-tests ]
    uses: ./.github/workflows/deploy-to-paas.yml
    with:
      environment: test
      cf-space-name: product-pages-test
      url: https://di-product-page-test.london.cloudapps.digital
    secrets:
      cf-username: ${{ secrets.CF_USERNAME }}
      cf-password: ${{ secrets.CF_PASSWORD }}
      register-spreadsheet-id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      mailing-list-spreadsheet-id: ${{ secrets.MAILING_LIST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-test
    uses: ./.github/workflows/run-acceptance-tests.yml
    with:
      host: ${{ needs.deploy-test.outputs.deployment-url }}

  deploy-production:
    name: Publish
    needs: run-acceptance-tests
    uses: ./.github/workflows/deploy-to-paas.yml
    with:
      environment: production
      cf-space-name: product-pages-production
      url: https://www.sign-in.service.gov.uk
      google-tag-id: GTM-W38DXV2
      use-stub-zendesk: false
      rolling-deployment: true
      instances: 3
    secrets:
      cf-username: ${{ secrets.CF_USERNAME }}
      cf-password: ${{ secrets.CF_PASSWORD }}
      zendesk-group-id: ${{ secrets.ZENDESK_GROUP_ID }}
      zendesk-username: ${{ secrets.ZENDESK_USERNAME }}
      zendesk-api-token: ${{ secrets.ZENDESK_API_TOKEN }}
      register-spreadsheet-id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      mailing-list-spreadsheet-id: ${{ secrets.MAILING_LIST_SPREADSHEET_ID }}
