name: Acceptance tests

on:
  workflow_call:
    inputs:
      host: { required: true, type: string }
      environment: { required: true, type: string }

concurrency: deploy-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write
  contents: read

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Run cucumber tests
        env:
          HOST: ${{ inputs.deployment-url-output }}
        run: npm run cucumber
