name: Acceptance tests

on:
  workflow_call:
    inputs:
      host: { required: true, type: string }
      environment: { required: true, type: string }

concurrency: deploy-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write
  contents: read

jobs:
  run-acceptance-tests:
    # GitHub's status checks should be disabled for merge checks - https://github.com/orgs/community/discussions/103114
    if: github.event_name != 'merge_group'
    name: Acceptance
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Run cucumber tests
        env:
          HOST: ${{ inputs.host }}
        run: npm run cucumber
