name: Acceptance tests

on:
  workflow_call:
    #inputs:
      #host: { required: true, type: string }
      #environment: { required: true, type: string }

concurrency: deploy-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}
permissions:
  id-token: write
  contents: read

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      #- name: Verify HOST variable
        #run: | 
          #echo "HOST: ${{ needs.deploy-frontend.outputs.deployment-url-output }}"

      #- name: Set HOST based on branch
        #run: echo "HOST=https://preview-${{ github.head_ref || github.ref_name }}.development.sign-in.service.gov.uk" >> $GITHUB_ENV


      - name: Run Cucumber Tests
        #run: |
          #npm run cucumber --env PRODUCT_TOOL_URL="${{ needs.deploy-Frontend.outputs.ProductToolURL }}
        env:
          HOST: ${{ https://preview-${{ github.head_ref || github.ref_name }}.development.sign-in.service.gov.uk }}
        run: npm run cucumber

