name: Unit tests

on: workflow_call
permissions: #read-all
  id-token: write
  contents: read

concurrency:
  group: unit-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Run mocha tests
        run: npm run test
